### ISSUE TITLE
[Nitpick] Strange if syntax

### ISSUE THREAD

**Issue by BeanGirlThing** [sRemorse/RemorseUtils#2]
https://github.com/sRemorse/RemorseUtils/blob/dffb68b2ee41829327a6da8a14bc7ad40354cc5b/src/main/java/com/remorse/remorseutils/Commands/God/GodCommand.java#L17

Unsure why you have `if(sender instanceof Player player) {` defined rather than `if(sender instanceof Player) {` once you have validated that sender is an instance of player, you can just use the sender object for following lines rather than creating a new variable.

**Comment by sRemorse** [comment]
This is necessary to access the player object to check the hasPermission and also the toggleGod method below on line 23
