### ISSUE TITLE
[Nitpick] Unnecessary permission validation

### ISSUE THREAD

**Issue by BeanGirlThing** [sRemorse/RemorseUtils#3]
https://github.com/sRemorse/RemorseUtils/blob/dffb68b2ee41829327a6da8a14bc7ad40354cc5b/src/main/java/com/remorse/remorseutils/Commands/God/GodCommand.java#L18

Where you have validated the permission here is not actually neccisary, as that is just using the command without trying to use it on others, spigot checks this itself before the command is run, validating permissions is only needed if you have separate permissions for using the command in a certain way, like on others, for example, what you have done on line 29 is correct! As that is something spigot will not check on its own.

**Comment by BeanGirlThing** [comment]
Same issue is present in a few other commands

**Comment by sRemorse** [comment]
Leaving this in as I'm not defining permission under the command within the plugin.yml and doing it in here instead this allows the custom message.

**Comment by BeanGirlThing** [comment]
You can define a permission message for each command within the plugin yml, if you refer to mine here: https://github.com/BeanGirlThing/FerretPlugin/blob/main/src/main/resources/plugin.yml
